In [3]:
#0-D array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#1-D array
import numpy as np
arr=np.array (42)
print(arr)

42


In [6]:
#2-D array

import numpy as np
arr=np.array([[1,2,3,],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
#3-D array

import numpy as np
arr=np.array([[[1,2,3,],[4,5,6],[1,2,3,],[4,5,6,]]])
print(arr)


[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [21]:
#it provides the dimensions of array

import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)      

0
1
2
3


In [24]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[1])


2


In [25]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr[0])

1


In [26]:
import numpy as np

arr=np.array([1,2,3,4])

print(arr[2]+arr[3])

7


In [31]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on 1st row:', arr[0,1])
    

2nd element on 1st row: 2


In [32]:
#slicing

import numpy as np

arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [35]:
#here start index has not been mentioned
import numpy as np
arr = np. array ([1, 2, 3, 4, 5, 6, 7])
print (arr[:51])


[1 2 3 4 5 6 7]


In [40]:
# When start and end both are not mentioned
impor

[1 2 3 4 5 6 7]


In [42]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])

[5 6 7]


In [43]:
import numpy as np
arr = np. array ([1, 2, 3, 4, 5, 6, 7])
print (arr[-3:-1])

[5 6]


In [44]:
import numpy as np
arr = np. array ([1, 2, 3, 4, 5, 6, 7])
print (arr[1:5:2])

[2 4]


In [55]:
import numpy as np
arr = np. array ([1, 2, 3, 4, 5, 6, 7])
print (arr[::2])

[1 3 5 7]


In [1]:
#slicing 2-D array 

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [7]:
#select  the element at row index 1

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

element = arr[1,2]

print(element)

6


In [8]:
import numpy as np

arr = np.array([[1,2,3],[3,4,5],[7,8,9]])

row_slice = arr[0:2, :]

print(row_slice) 

[[1 2 3]
 [3 4 5]]


In [9]:
import numpy as np

arr = np.array([[1,2,3],[3,4,5],[7,8,9]])
col_slice = arr[:,1:3]
print (col_slice)


[[2 3]
 [4 5]
 [8 9]]
